#!/bin/sh
case "$1" in
  start)
    /usr/sbin/wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
    udhcpc -b -i wlan0
    ;;
  stop) killall udhcpc wpa_supplicant ;;
  restart) $0 stop; $0 start ;;
esac
exit 0
